trigger:
- none
pool:
  vmImage: ubuntu-latest
parameters:
  - name: VERSION
    type: string
    default: "" 
steps:
- script: |
   whoami
   echo $(Pipeline.Workspace)
   echo $(Build.SourceBranchName)
   echo $(Build.SourcesDirectory)
   echo ${{ parameters.VERSION }}
   ls -ltra
  displayName: 'First' 
- script: | 
   mvn versions:set -DnewVersion=${{ parameters.VERSION }}
   mvn package
   ls -ltra
   cd ./module1/target
   ls -ltra
   cd $(Build.SourcesDirectory)/module2/target/surefire-reports
   ls -ltra
   echo maven build completed
  displayName: 'build'
- script: | 
   cd $(Pipeline.Workspace)/a
   ls -ltra
   echo workspace artifactory staging directory
   cd $(Pipeline.Workspace)/b
   ls -ltra
   echo workspace binary directory
  displayName: 'test'
- script: | 
   cd $(Build.SourcesDirectory)
   mvn clean
   cd ./module1/
   ls -ltra
   cd $(Build.SourcesDirectory)/module2/
   ls -ltra
   echo maven clean completed
  displayName: 'clean' 

