trigger:
- none
pool:
  vmImage: ubuntu-latest
parameters:
  - name: VERSION
    type: string
    default:  
steps:
- script: |
   whoami
   echo $(Pipeline.Workspace)
   echo $(Build.SourceBranchName)
   echo $(Build.SourcesDirectory)
   echo ${{ parameters.VERSION }}
   ls -ltra
  displayName: 'testing' 
- script: | 
   mvn versions:set -DnewVersion=${{ parameters.VERSION }}
   mvn install
   cd ./module1/target
   ls -ltra
   cd $(Build.SourcesDirectory)/module2/target
   ls -ltra
   echo maven build completed
  displayName: 'build'

- script: | 
  
   mvn clean
   cd ./module1/
   ls -ltra
   cd $(Build.SourcesDirectory)/module2/
   ls -ltra
   echo maven clean completed
  displayName: 'clean' 
