trigger:
- none
pool:
  vmImage: ubuntu-latest
steps:
- script: |
   whoami
   echo $(Pipeline.Workspace)
   echo $(Build.SourceBranchName)
   echo $(Build.SourcesDirectory)
   ls -ltra
  displayName: 'testing' 
- script: | 
  
   mvn install
   cd ./module1/target
   ls -ltra
   echo maven build completed
   
